// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package config

import (
	"errors"
	"fmt"
)

const (
	// ExportTypeYml is a ExportType of type Yml.
	ExportTypeYml ExportType = iota
	// ExportTypeJson is a ExportType of type Json.
	ExportTypeJson
	// ExportTypeEnv is a ExportType of type Env.
	ExportTypeEnv
)

var ErrInvalidExportType = errors.New("not a valid ExportType")

const _ExportTypeName = "ymljsonenv"

var _ExportTypeMap = map[ExportType]string{
	ExportTypeYml:  _ExportTypeName[0:3],
	ExportTypeJson: _ExportTypeName[3:7],
	ExportTypeEnv:  _ExportTypeName[7:10],
}

// String implements the Stringer interface.
func (x ExportType) String() string {
	if str, ok := _ExportTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ExportType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ExportType) IsValid() bool {
	_, ok := _ExportTypeMap[x]
	return ok
}

var _ExportTypeValue = map[string]ExportType{
	_ExportTypeName[0:3]:  ExportTypeYml,
	_ExportTypeName[3:7]:  ExportTypeJson,
	_ExportTypeName[7:10]: ExportTypeEnv,
}

// ParseExportType attempts to convert a string to a ExportType.
func ParseExportType(name string) (ExportType, error) {
	if x, ok := _ExportTypeValue[name]; ok {
		return x, nil
	}
	return ExportType(0), fmt.Errorf("%s is %w", name, ErrInvalidExportType)
}
